apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demofml-development-work-v1
  namespace: demofml
  labels:
    app.kubernetes.io/name: development-pipeline
    app.kubernetes.io/part-of: demofml
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 64Gi
